var price = 000;
console.log(price);
var age = 23;
console.log(age);
var height = 6;
console.log(height);
var weight = 84;
console.log(weight);
var nam = 'mofazzal';
console.log(nam);
var address = 'Dhaka';
console.log(address);
var fail = true;
console.log(fail);
var pass = false;
console.log(pass);